name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        TZ=":America/New_York" date
        timestamp=$(date)
        curl https://display.safespace.io/value/live/a7796f34 >> occupancy.csv
        echo ", ${timestamp}" >> occupancy.csv
    - name: Commit and push if it changed
      run: |-
        TZ=":America/New_York" date
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
